// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wasm.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 合约对象信息
type WASMContractObject struct {
	Addr                 string             `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Data                 *WASMContractData  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	State                *WASMContractState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WASMContractObject) Reset()         { *m = WASMContractObject{} }
func (m *WASMContractObject) String() string { return proto.CompactTextString(m) }
func (*WASMContractObject) ProtoMessage()    {}
func (*WASMContractObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{0}
}
func (m *WASMContractObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WASMContractObject.Unmarshal(m, b)
}
func (m *WASMContractObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WASMContractObject.Marshal(b, m, deterministic)
}
func (dst *WASMContractObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WASMContractObject.Merge(dst, src)
}
func (m *WASMContractObject) XXX_Size() int {
	return xxx_messageInfo_WASMContractObject.Size(m)
}
func (m *WASMContractObject) XXX_DiscardUnknown() {
	xxx_messageInfo_WASMContractObject.DiscardUnknown(m)
}

var xxx_messageInfo_WASMContractObject proto.InternalMessageInfo

func (m *WASMContractObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WASMContractObject) GetData() *WASMContractData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WASMContractObject) GetState() *WASMContractState {
	if m != nil {
		return m.State
	}
	return nil
}

// 存放合约固定数据
type WASMContractData struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Code                 []byte   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash             []byte   `protobuf:"bytes,6,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	Abi                  []byte   `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WASMContractData) Reset()         { *m = WASMContractData{} }
func (m *WASMContractData) String() string { return proto.CompactTextString(m) }
func (*WASMContractData) ProtoMessage()    {}
func (*WASMContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{1}
}
func (m *WASMContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WASMContractData.Unmarshal(m, b)
}
func (m *WASMContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WASMContractData.Marshal(b, m, deterministic)
}
func (dst *WASMContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WASMContractData.Merge(dst, src)
}
func (m *WASMContractData) XXX_Size() int {
	return xxx_messageInfo_WASMContractData.Size(m)
}
func (m *WASMContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_WASMContractData.DiscardUnknown(m)
}

var xxx_messageInfo_WASMContractData proto.InternalMessageInfo

func (m *WASMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *WASMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WASMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WASMContractData) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *WASMContractData) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *WASMContractData) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type LogWASMContractData struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	CodeHash             string   `protobuf:"bytes,4,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	AbiHash              string   `protobuf:"bytes,5,opt,name=abiHash,proto3" json:"abiHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogWASMContractData) Reset()         { *m = LogWASMContractData{} }
func (m *LogWASMContractData) String() string { return proto.CompactTextString(m) }
func (*LogWASMContractData) ProtoMessage()    {}
func (*LogWASMContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{2}
}
func (m *LogWASMContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogWASMContractData.Unmarshal(m, b)
}
func (m *LogWASMContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogWASMContractData.Marshal(b, m, deterministic)
}
func (dst *LogWASMContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogWASMContractData.Merge(dst, src)
}
func (m *LogWASMContractData) XXX_Size() int {
	return xxx_messageInfo_LogWASMContractData.Size(m)
}
func (m *LogWASMContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogWASMContractData.DiscardUnknown(m)
}

var xxx_messageInfo_LogWASMContractData proto.InternalMessageInfo

func (m *LogWASMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *LogWASMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogWASMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *LogWASMContractData) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *LogWASMContractData) GetAbiHash() string {
	if m != nil {
		return m.AbiHash
	}
	return ""
}

// 存放合约变化数据
type WASMContractState struct {
	Nonce                uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Suicided             bool              `protobuf:"varint,2,opt,name=suicided,proto3" json:"suicided,omitempty"`
	Storage              map[string][]byte `protobuf:"bytes,3,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WASMContractState) Reset()         { *m = WASMContractState{} }
func (m *WASMContractState) String() string { return proto.CompactTextString(m) }
func (*WASMContractState) ProtoMessage()    {}
func (*WASMContractState) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{3}
}
func (m *WASMContractState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WASMContractState.Unmarshal(m, b)
}
func (m *WASMContractState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WASMContractState.Marshal(b, m, deterministic)
}
func (dst *WASMContractState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WASMContractState.Merge(dst, src)
}
func (m *WASMContractState) XXX_Size() int {
	return xxx_messageInfo_WASMContractState.Size(m)
}
func (m *WASMContractState) XXX_DiscardUnknown() {
	xxx_messageInfo_WASMContractState.DiscardUnknown(m)
}

var xxx_messageInfo_WASMContractState proto.InternalMessageInfo

func (m *WASMContractState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *WASMContractState) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *WASMContractState) GetStorage() map[string][]byte {
	if m != nil {
		return m.Storage
	}
	return nil
}

type WasmContractAction struct {
	// Types that are valid to be assigned to Value:
	//	*WasmContractAction_CreateWasmContract
	//	*WasmContractAction_CallWasmContract
	Value                isWasmContractAction_Value `protobuf_oneof:"value"`
	Ty                   int32                      `protobuf:"varint,3,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *WasmContractAction) Reset()         { *m = WasmContractAction{} }
func (m *WasmContractAction) String() string { return proto.CompactTextString(m) }
func (*WasmContractAction) ProtoMessage()    {}
func (*WasmContractAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{4}
}
func (m *WasmContractAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmContractAction.Unmarshal(m, b)
}
func (m *WasmContractAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmContractAction.Marshal(b, m, deterministic)
}
func (dst *WasmContractAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmContractAction.Merge(dst, src)
}
func (m *WasmContractAction) XXX_Size() int {
	return xxx_messageInfo_WasmContractAction.Size(m)
}
func (m *WasmContractAction) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmContractAction.DiscardUnknown(m)
}

var xxx_messageInfo_WasmContractAction proto.InternalMessageInfo

type isWasmContractAction_Value interface {
	isWasmContractAction_Value()
}

type WasmContractAction_CreateWasmContract struct {
	CreateWasmContract *CreateWasmContract `protobuf:"bytes,1,opt,name=createWasmContract,proto3,oneof"`
}

type WasmContractAction_CallWasmContract struct {
	CallWasmContract *CallWasmContract `protobuf:"bytes,2,opt,name=callWasmContract,proto3,oneof"`
}

func (*WasmContractAction_CreateWasmContract) isWasmContractAction_Value() {}

func (*WasmContractAction_CallWasmContract) isWasmContractAction_Value() {}

func (m *WasmContractAction) GetValue() isWasmContractAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WasmContractAction) GetCreateWasmContract() *CreateWasmContract {
	if x, ok := m.GetValue().(*WasmContractAction_CreateWasmContract); ok {
		return x.CreateWasmContract
	}
	return nil
}

func (m *WasmContractAction) GetCallWasmContract() *CallWasmContract {
	if x, ok := m.GetValue().(*WasmContractAction_CallWasmContract); ok {
		return x.CallWasmContract
	}
	return nil
}

func (m *WasmContractAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WasmContractAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WasmContractAction_OneofMarshaler, _WasmContractAction_OneofUnmarshaler, _WasmContractAction_OneofSizer, []interface{}{
		(*WasmContractAction_CreateWasmContract)(nil),
		(*WasmContractAction_CallWasmContract)(nil),
	}
}

func _WasmContractAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WasmContractAction)
	// value
	switch x := m.Value.(type) {
	case *WasmContractAction_CreateWasmContract:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateWasmContract); err != nil {
			return err
		}
	case *WasmContractAction_CallWasmContract:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CallWasmContract); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WasmContractAction.Value has unexpected type %T", x)
	}
	return nil
}

func _WasmContractAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WasmContractAction)
	switch tag {
	case 1: // value.createWasmContract
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateWasmContract)
		err := b.DecodeMessage(msg)
		m.Value = &WasmContractAction_CreateWasmContract{msg}
		return true, err
	case 2: // value.callWasmContract
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CallWasmContract)
		err := b.DecodeMessage(msg)
		m.Value = &WasmContractAction_CallWasmContract{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WasmContractAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WasmContractAction)
	// value
	switch x := m.Value.(type) {
	case *WasmContractAction_CreateWasmContract:
		s := proto.Size(x.CreateWasmContract)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WasmContractAction_CallWasmContract:
		s := proto.Size(x.CallWasmContract)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 创建wasm合约
type CreateWasmContract struct {
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,1,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,2,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 合约数据
	Code []byte `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// abi数据
	Abi string `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`
	// 用户自定义wasm合约名字，必须是user.wasm.xxx的风格，且xxx由a-z，0-9组成的4-16字符长度组成
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 交易备注
	Note                 string   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWasmContract) Reset()         { *m = CreateWasmContract{} }
func (m *CreateWasmContract) String() string { return proto.CompactTextString(m) }
func (*CreateWasmContract) ProtoMessage()    {}
func (*CreateWasmContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{5}
}
func (m *CreateWasmContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWasmContract.Unmarshal(m, b)
}
func (m *CreateWasmContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWasmContract.Marshal(b, m, deterministic)
}
func (dst *CreateWasmContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWasmContract.Merge(dst, src)
}
func (m *CreateWasmContract) XXX_Size() int {
	return xxx_messageInfo_CreateWasmContract.Size(m)
}
func (m *CreateWasmContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWasmContract.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWasmContract proto.InternalMessageInfo

func (m *CreateWasmContract) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateWasmContract) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CreateWasmContract) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateWasmContract) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateWasmContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateWasmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 调用wasm合约
type CallWasmContract struct {
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,1,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,2,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	// 虚拟机解释器类型
	VmType int32 `protobuf:"varint,4,opt,name=vmType,proto3" json:"vmType,omitempty"`
	// 执行动作名称
	ActionName string `protobuf:"bytes,5,opt,name=actionName,proto3" json:"actionName,omitempty"`
	// 执行参数
	ActionData           []byte   `protobuf:"bytes,6,opt,name=actionData,proto3" json:"actionData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallWasmContract) Reset()         { *m = CallWasmContract{} }
func (m *CallWasmContract) String() string { return proto.CompactTextString(m) }
func (*CallWasmContract) ProtoMessage()    {}
func (*CallWasmContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{6}
}
func (m *CallWasmContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallWasmContract.Unmarshal(m, b)
}
func (m *CallWasmContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallWasmContract.Marshal(b, m, deterministic)
}
func (dst *CallWasmContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallWasmContract.Merge(dst, src)
}
func (m *CallWasmContract) XXX_Size() int {
	return xxx_messageInfo_CallWasmContract.Size(m)
}
func (m *CallWasmContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CallWasmContract.DiscardUnknown(m)
}

var xxx_messageInfo_CallWasmContract proto.InternalMessageInfo

func (m *CallWasmContract) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CallWasmContract) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CallWasmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CallWasmContract) GetVmType() int32 {
	if m != nil {
		return m.VmType
	}
	return 0
}

func (m *CallWasmContract) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *CallWasmContract) GetActionData() []byte {
	if m != nil {
		return m.ActionData
	}
	return nil
}

// 存放本地数据库的数据
type ReceiptLocalData struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CurValue             []byte   `protobuf:"bytes,2,opt,name=curValue,proto3" json:"curValue,omitempty"`
	PreValue             []byte   `protobuf:"bytes,3,opt,name=preValue,proto3" json:"preValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptLocalData) Reset()         { *m = ReceiptLocalData{} }
func (m *ReceiptLocalData) String() string { return proto.CompactTextString(m) }
func (*ReceiptLocalData) ProtoMessage()    {}
func (*ReceiptLocalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{7}
}
func (m *ReceiptLocalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptLocalData.Unmarshal(m, b)
}
func (m *ReceiptLocalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptLocalData.Marshal(b, m, deterministic)
}
func (dst *ReceiptLocalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptLocalData.Merge(dst, src)
}
func (m *ReceiptLocalData) XXX_Size() int {
	return xxx_messageInfo_ReceiptLocalData.Size(m)
}
func (m *ReceiptLocalData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptLocalData.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptLocalData proto.InternalMessageInfo

func (m *ReceiptLocalData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReceiptLocalData) GetCurValue() []byte {
	if m != nil {
		return m.CurValue
	}
	return nil
}

func (m *ReceiptLocalData) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

// 合约创建/调用日志
type ReceiptWASMContract struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	ContractName         string   `protobuf:"bytes,2,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ContractAddr         string   `protobuf:"bytes,3,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	UsedGas              uint64   `protobuf:"varint,4,opt,name=usedGas,proto3" json:"usedGas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptWASMContract) Reset()         { *m = ReceiptWASMContract{} }
func (m *ReceiptWASMContract) String() string { return proto.CompactTextString(m) }
func (*ReceiptWASMContract) ProtoMessage()    {}
func (*ReceiptWASMContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{8}
}
func (m *ReceiptWASMContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptWASMContract.Unmarshal(m, b)
}
func (m *ReceiptWASMContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptWASMContract.Marshal(b, m, deterministic)
}
func (dst *ReceiptWASMContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptWASMContract.Merge(dst, src)
}
func (m *ReceiptWASMContract) XXX_Size() int {
	return xxx_messageInfo_ReceiptWASMContract.Size(m)
}
func (m *ReceiptWASMContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptWASMContract.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptWASMContract proto.InternalMessageInfo

func (m *ReceiptWASMContract) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptWASMContract) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptWASMContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ReceiptWASMContract) GetUsedGas() uint64 {
	if m != nil {
		return m.UsedGas
	}
	return 0
}

// 用于保存WASM只能合约中的状态数据变更
type WASMStateChangeItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PreValue             []byte   `protobuf:"bytes,2,opt,name=preValue,proto3" json:"preValue,omitempty"`
	CurrentValue         []byte   `protobuf:"bytes,3,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WASMStateChangeItem) Reset()         { *m = WASMStateChangeItem{} }
func (m *WASMStateChangeItem) String() string { return proto.CompactTextString(m) }
func (*WASMStateChangeItem) ProtoMessage()    {}
func (*WASMStateChangeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{9}
}
func (m *WASMStateChangeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WASMStateChangeItem.Unmarshal(m, b)
}
func (m *WASMStateChangeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WASMStateChangeItem.Marshal(b, m, deterministic)
}
func (dst *WASMStateChangeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WASMStateChangeItem.Merge(dst, src)
}
func (m *WASMStateChangeItem) XXX_Size() int {
	return xxx_messageInfo_WASMStateChangeItem.Size(m)
}
func (m *WASMStateChangeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_WASMStateChangeItem.DiscardUnknown(m)
}

var xxx_messageInfo_WASMStateChangeItem proto.InternalMessageInfo

func (m *WASMStateChangeItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WASMStateChangeItem) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

func (m *WASMStateChangeItem) GetCurrentValue() []byte {
	if m != nil {
		return m.CurrentValue
	}
	return nil
}

type CheckWASMContractNameReq struct {
	WasmContractName     string   `protobuf:"bytes,1,opt,name=WasmContractName,proto3" json:"WasmContractName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWASMContractNameReq) Reset()         { *m = CheckWASMContractNameReq{} }
func (m *CheckWASMContractNameReq) String() string { return proto.CompactTextString(m) }
func (*CheckWASMContractNameReq) ProtoMessage()    {}
func (*CheckWASMContractNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{10}
}
func (m *CheckWASMContractNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWASMContractNameReq.Unmarshal(m, b)
}
func (m *CheckWASMContractNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWASMContractNameReq.Marshal(b, m, deterministic)
}
func (dst *CheckWASMContractNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWASMContractNameReq.Merge(dst, src)
}
func (m *CheckWASMContractNameReq) XXX_Size() int {
	return xxx_messageInfo_CheckWASMContractNameReq.Size(m)
}
func (m *CheckWASMContractNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWASMContractNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWASMContractNameReq proto.InternalMessageInfo

func (m *CheckWASMContractNameReq) GetWasmContractName() string {
	if m != nil {
		return m.WasmContractName
	}
	return ""
}

type CheckWASMAddrResp struct {
	ExistAlready         bool     `protobuf:"varint,1,opt,name=existAlready,proto3" json:"existAlready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWASMAddrResp) Reset()         { *m = CheckWASMAddrResp{} }
func (m *CheckWASMAddrResp) String() string { return proto.CompactTextString(m) }
func (*CheckWASMAddrResp) ProtoMessage()    {}
func (*CheckWASMAddrResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{11}
}
func (m *CheckWASMAddrResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWASMAddrResp.Unmarshal(m, b)
}
func (m *CheckWASMAddrResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWASMAddrResp.Marshal(b, m, deterministic)
}
func (dst *CheckWASMAddrResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWASMAddrResp.Merge(dst, src)
}
func (m *CheckWASMAddrResp) XXX_Size() int {
	return xxx_messageInfo_CheckWASMAddrResp.Size(m)
}
func (m *CheckWASMAddrResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWASMAddrResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWASMAddrResp proto.InternalMessageInfo

func (m *CheckWASMAddrResp) GetExistAlready() bool {
	if m != nil {
		return m.ExistAlready
	}
	return false
}

type EstimateWASMGasReq struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Code                 []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Caller               string   `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateWASMGasReq) Reset()         { *m = EstimateWASMGasReq{} }
func (m *EstimateWASMGasReq) String() string { return proto.CompactTextString(m) }
func (*EstimateWASMGasReq) ProtoMessage()    {}
func (*EstimateWASMGasReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{12}
}
func (m *EstimateWASMGasReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateWASMGasReq.Unmarshal(m, b)
}
func (m *EstimateWASMGasReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateWASMGasReq.Marshal(b, m, deterministic)
}
func (dst *EstimateWASMGasReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateWASMGasReq.Merge(dst, src)
}
func (m *EstimateWASMGasReq) XXX_Size() int {
	return xxx_messageInfo_EstimateWASMGasReq.Size(m)
}
func (m *EstimateWASMGasReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateWASMGasReq.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateWASMGasReq proto.InternalMessageInfo

func (m *EstimateWASMGasReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EstimateWASMGasReq) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EstimateWASMGasReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EstimateWASMGasReq) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type EstimateWASMGasResp struct {
	Gas                  uint64   `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateWASMGasResp) Reset()         { *m = EstimateWASMGasResp{} }
func (m *EstimateWASMGasResp) String() string { return proto.CompactTextString(m) }
func (*EstimateWASMGasResp) ProtoMessage()    {}
func (*EstimateWASMGasResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{13}
}
func (m *EstimateWASMGasResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateWASMGasResp.Unmarshal(m, b)
}
func (m *EstimateWASMGasResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateWASMGasResp.Marshal(b, m, deterministic)
}
func (dst *EstimateWASMGasResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateWASMGasResp.Merge(dst, src)
}
func (m *EstimateWASMGasResp) XXX_Size() int {
	return xxx_messageInfo_EstimateWASMGasResp.Size(m)
}
func (m *EstimateWASMGasResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateWASMGasResp.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateWASMGasResp proto.InternalMessageInfo

func (m *EstimateWASMGasResp) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

type WasmDebugReq struct {
	// 0 query, 1 set, -1 clear
	Optype               int32    `protobuf:"varint,1,opt,name=optype,proto3" json:"optype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmDebugReq) Reset()         { *m = WasmDebugReq{} }
func (m *WasmDebugReq) String() string { return proto.CompactTextString(m) }
func (*WasmDebugReq) ProtoMessage()    {}
func (*WasmDebugReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{14}
}
func (m *WasmDebugReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmDebugReq.Unmarshal(m, b)
}
func (m *WasmDebugReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmDebugReq.Marshal(b, m, deterministic)
}
func (dst *WasmDebugReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmDebugReq.Merge(dst, src)
}
func (m *WasmDebugReq) XXX_Size() int {
	return xxx_messageInfo_WasmDebugReq.Size(m)
}
func (m *WasmDebugReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmDebugReq.DiscardUnknown(m)
}

var xxx_messageInfo_WasmDebugReq proto.InternalMessageInfo

func (m *WasmDebugReq) GetOptype() int32 {
	if m != nil {
		return m.Optype
	}
	return 0
}

type WasmDebugResp struct {
	DebugStatus          string   `protobuf:"bytes,1,opt,name=debugStatus,proto3" json:"debugStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmDebugResp) Reset()         { *m = WasmDebugResp{} }
func (m *WasmDebugResp) String() string { return proto.CompactTextString(m) }
func (*WasmDebugResp) ProtoMessage()    {}
func (*WasmDebugResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{15}
}
func (m *WasmDebugResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmDebugResp.Unmarshal(m, b)
}
func (m *WasmDebugResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmDebugResp.Marshal(b, m, deterministic)
}
func (dst *WasmDebugResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmDebugResp.Merge(dst, src)
}
func (m *WasmDebugResp) XXX_Size() int {
	return xxx_messageInfo_WasmDebugResp.Size(m)
}
func (m *WasmDebugResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmDebugResp.DiscardUnknown(m)
}

var xxx_messageInfo_WasmDebugResp proto.InternalMessageInfo

func (m *WasmDebugResp) GetDebugStatus() string {
	if m != nil {
		return m.DebugStatus
	}
	return ""
}

type WasmGetAbiResp struct {
	Abi                  []byte   `protobuf:"bytes,1,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmGetAbiResp) Reset()         { *m = WasmGetAbiResp{} }
func (m *WasmGetAbiResp) String() string { return proto.CompactTextString(m) }
func (*WasmGetAbiResp) ProtoMessage()    {}
func (*WasmGetAbiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{16}
}
func (m *WasmGetAbiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmGetAbiResp.Unmarshal(m, b)
}
func (m *WasmGetAbiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmGetAbiResp.Marshal(b, m, deterministic)
}
func (dst *WasmGetAbiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmGetAbiResp.Merge(dst, src)
}
func (m *WasmGetAbiResp) XXX_Size() int {
	return xxx_messageInfo_WasmGetAbiResp.Size(m)
}
func (m *WasmGetAbiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmGetAbiResp.DiscardUnknown(m)
}

var xxx_messageInfo_WasmGetAbiResp proto.InternalMessageInfo

func (m *WasmGetAbiResp) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type WasmQueryTableItem struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmQueryTableItem) Reset()         { *m = WasmQueryTableItem{} }
func (m *WasmQueryTableItem) String() string { return proto.CompactTextString(m) }
func (*WasmQueryTableItem) ProtoMessage()    {}
func (*WasmQueryTableItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{17}
}
func (m *WasmQueryTableItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmQueryTableItem.Unmarshal(m, b)
}
func (m *WasmQueryTableItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmQueryTableItem.Marshal(b, m, deterministic)
}
func (dst *WasmQueryTableItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmQueryTableItem.Merge(dst, src)
}
func (m *WasmQueryTableItem) XXX_Size() int {
	return xxx_messageInfo_WasmQueryTableItem.Size(m)
}
func (m *WasmQueryTableItem) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmQueryTableItem.DiscardUnknown(m)
}

var xxx_messageInfo_WasmQueryTableItem proto.InternalMessageInfo

func (m *WasmQueryTableItem) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *WasmQueryTableItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type WasmQueryContractTableReq struct {
	ContractName         string                `protobuf:"bytes,1,opt,name=contractName,proto3" json:"contractName,omitempty"`
	Items                []*WasmQueryTableItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WasmQueryContractTableReq) Reset()         { *m = WasmQueryContractTableReq{} }
func (m *WasmQueryContractTableReq) String() string { return proto.CompactTextString(m) }
func (*WasmQueryContractTableReq) ProtoMessage()    {}
func (*WasmQueryContractTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{18}
}
func (m *WasmQueryContractTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmQueryContractTableReq.Unmarshal(m, b)
}
func (m *WasmQueryContractTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmQueryContractTableReq.Marshal(b, m, deterministic)
}
func (dst *WasmQueryContractTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmQueryContractTableReq.Merge(dst, src)
}
func (m *WasmQueryContractTableReq) XXX_Size() int {
	return xxx_messageInfo_WasmQueryContractTableReq.Size(m)
}
func (m *WasmQueryContractTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmQueryContractTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_WasmQueryContractTableReq proto.InternalMessageInfo

func (m *WasmQueryContractTableReq) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *WasmQueryContractTableReq) GetItems() []*WasmQueryTableItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type WasmOutItem struct {
	ItemType             string   `protobuf:"bytes,1,opt,name=ItemType,proto3" json:"ItemType,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmOutItem) Reset()         { *m = WasmOutItem{} }
func (m *WasmOutItem) String() string { return proto.CompactTextString(m) }
func (*WasmOutItem) ProtoMessage()    {}
func (*WasmOutItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{19}
}
func (m *WasmOutItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmOutItem.Unmarshal(m, b)
}
func (m *WasmOutItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmOutItem.Marshal(b, m, deterministic)
}
func (dst *WasmOutItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmOutItem.Merge(dst, src)
}
func (m *WasmOutItem) XXX_Size() int {
	return xxx_messageInfo_WasmOutItem.Size(m)
}
func (m *WasmOutItem) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmOutItem.DiscardUnknown(m)
}

var xxx_messageInfo_WasmOutItem proto.InternalMessageInfo

func (m *WasmOutItem) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *WasmOutItem) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryResultItem struct {
	ItemType             string   `protobuf:"bytes,1,opt,name=ItemType,proto3" json:"ItemType,omitempty"`
	ResultJSON           string   `protobuf:"bytes,2,opt,name=resultJSON,proto3" json:"resultJSON,omitempty"`
	Found                bool     `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResultItem) Reset()         { *m = QueryResultItem{} }
func (m *QueryResultItem) String() string { return proto.CompactTextString(m) }
func (*QueryResultItem) ProtoMessage()    {}
func (*QueryResultItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{20}
}
func (m *QueryResultItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultItem.Unmarshal(m, b)
}
func (m *QueryResultItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultItem.Marshal(b, m, deterministic)
}
func (dst *QueryResultItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultItem.Merge(dst, src)
}
func (m *QueryResultItem) XXX_Size() int {
	return xxx_messageInfo_QueryResultItem.Size(m)
}
func (m *QueryResultItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultItem proto.InternalMessageInfo

func (m *QueryResultItem) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *QueryResultItem) GetResultJSON() string {
	if m != nil {
		return m.ResultJSON
	}
	return ""
}

func (m *QueryResultItem) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type WasmQueryResponse struct {
	QueryResultItems     []*QueryResultItem `protobuf:"bytes,1,rep,name=queryResultItems,proto3" json:"queryResultItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WasmQueryResponse) Reset()         { *m = WasmQueryResponse{} }
func (m *WasmQueryResponse) String() string { return proto.CompactTextString(m) }
func (*WasmQueryResponse) ProtoMessage()    {}
func (*WasmQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{21}
}
func (m *WasmQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmQueryResponse.Unmarshal(m, b)
}
func (m *WasmQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmQueryResponse.Marshal(b, m, deterministic)
}
func (dst *WasmQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmQueryResponse.Merge(dst, src)
}
func (m *WasmQueryResponse) XXX_Size() int {
	return xxx_messageInfo_WasmQueryResponse.Size(m)
}
func (m *WasmQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WasmQueryResponse proto.InternalMessageInfo

func (m *WasmQueryResponse) GetQueryResultItems() []*QueryResultItem {
	if m != nil {
		return m.QueryResultItems
	}
	return nil
}

type ConvertJson2AbiReq struct {
	ContractName         string   `protobuf:"bytes,1,opt,name=ContractName,proto3" json:"ContractName,omitempty"`
	ActionName           string   `protobuf:"bytes,2,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	AbiDataInJson        string   `protobuf:"bytes,3,opt,name=AbiDataInJson,proto3" json:"AbiDataInJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertJson2AbiReq) Reset()         { *m = ConvertJson2AbiReq{} }
func (m *ConvertJson2AbiReq) String() string { return proto.CompactTextString(m) }
func (*ConvertJson2AbiReq) ProtoMessage()    {}
func (*ConvertJson2AbiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{22}
}
func (m *ConvertJson2AbiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertJson2AbiReq.Unmarshal(m, b)
}
func (m *ConvertJson2AbiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertJson2AbiReq.Marshal(b, m, deterministic)
}
func (dst *ConvertJson2AbiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertJson2AbiReq.Merge(dst, src)
}
func (m *ConvertJson2AbiReq) XXX_Size() int {
	return xxx_messageInfo_ConvertJson2AbiReq.Size(m)
}
func (m *ConvertJson2AbiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertJson2AbiReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertJson2AbiReq proto.InternalMessageInfo

func (m *ConvertJson2AbiReq) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ConvertJson2AbiReq) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *ConvertJson2AbiReq) GetAbiDataInJson() string {
	if m != nil {
		return m.AbiDataInJson
	}
	return ""
}

type Json2AbiResponse struct {
	AbiData              []byte   `protobuf:"bytes,1,opt,name=AbiData,proto3" json:"AbiData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Json2AbiResponse) Reset()         { *m = Json2AbiResponse{} }
func (m *Json2AbiResponse) String() string { return proto.CompactTextString(m) }
func (*Json2AbiResponse) ProtoMessage()    {}
func (*Json2AbiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{23}
}
func (m *Json2AbiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Json2AbiResponse.Unmarshal(m, b)
}
func (m *Json2AbiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Json2AbiResponse.Marshal(b, m, deterministic)
}
func (dst *Json2AbiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Json2AbiResponse.Merge(dst, src)
}
func (m *Json2AbiResponse) XXX_Size() int {
	return xxx_messageInfo_Json2AbiResponse.Size(m)
}
func (m *Json2AbiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Json2AbiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Json2AbiResponse proto.InternalMessageInfo

func (m *Json2AbiResponse) GetAbiData() []byte {
	if m != nil {
		return m.AbiData
	}
	return nil
}

// 模糊查找请求
type WasmFuzzyQueryTableReq struct {
	ContractName         string   `protobuf:"bytes,1,opt,name=contractName,proto3" json:"contractName,omitempty"`
	TableName            string   `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Format               string   `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Start                int64    `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 int64    `protobuf:"varint,5,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmFuzzyQueryTableReq) Reset()         { *m = WasmFuzzyQueryTableReq{} }
func (m *WasmFuzzyQueryTableReq) String() string { return proto.CompactTextString(m) }
func (*WasmFuzzyQueryTableReq) ProtoMessage()    {}
func (*WasmFuzzyQueryTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{24}
}
func (m *WasmFuzzyQueryTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmFuzzyQueryTableReq.Unmarshal(m, b)
}
func (m *WasmFuzzyQueryTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmFuzzyQueryTableReq.Marshal(b, m, deterministic)
}
func (dst *WasmFuzzyQueryTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmFuzzyQueryTableReq.Merge(dst, src)
}
func (m *WasmFuzzyQueryTableReq) XXX_Size() int {
	return xxx_messageInfo_WasmFuzzyQueryTableReq.Size(m)
}
func (m *WasmFuzzyQueryTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmFuzzyQueryTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_WasmFuzzyQueryTableReq proto.InternalMessageInfo

func (m *WasmFuzzyQueryTableReq) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *WasmFuzzyQueryTableReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *WasmFuzzyQueryTableReq) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *WasmFuzzyQueryTableReq) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *WasmFuzzyQueryTableReq) GetStop() int64 {
	if m != nil {
		return m.Stop
	}
	return 0
}

type FuzzyQueryResultItem struct {
	// 模糊查找索引
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ResultJSON           []string `protobuf:"bytes,2,rep,name=resultJSON,proto3" json:"resultJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzyQueryResultItem) Reset()         { *m = FuzzyQueryResultItem{} }
func (m *FuzzyQueryResultItem) String() string { return proto.CompactTextString(m) }
func (*FuzzyQueryResultItem) ProtoMessage()    {}
func (*FuzzyQueryResultItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{25}
}
func (m *FuzzyQueryResultItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyQueryResultItem.Unmarshal(m, b)
}
func (m *FuzzyQueryResultItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyQueryResultItem.Marshal(b, m, deterministic)
}
func (dst *FuzzyQueryResultItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyQueryResultItem.Merge(dst, src)
}
func (m *FuzzyQueryResultItem) XXX_Size() int {
	return xxx_messageInfo_FuzzyQueryResultItem.Size(m)
}
func (m *FuzzyQueryResultItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyQueryResultItem.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyQueryResultItem proto.InternalMessageInfo

func (m *FuzzyQueryResultItem) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *FuzzyQueryResultItem) GetResultJSON() []string {
	if m != nil {
		return m.ResultJSON
	}
	return nil
}

type WasmFuzzyQueryResponse struct {
	ContractName         string                  `protobuf:"bytes,1,opt,name=contractName,proto3" json:"contractName,omitempty"`
	TableName            string                  `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	QueryResultItems     []*FuzzyQueryResultItem `protobuf:"bytes,3,rep,name=queryResultItems,proto3" json:"queryResultItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WasmFuzzyQueryResponse) Reset()         { *m = WasmFuzzyQueryResponse{} }
func (m *WasmFuzzyQueryResponse) String() string { return proto.CompactTextString(m) }
func (*WasmFuzzyQueryResponse) ProtoMessage()    {}
func (*WasmFuzzyQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{26}
}
func (m *WasmFuzzyQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmFuzzyQueryResponse.Unmarshal(m, b)
}
func (m *WasmFuzzyQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmFuzzyQueryResponse.Marshal(b, m, deterministic)
}
func (dst *WasmFuzzyQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmFuzzyQueryResponse.Merge(dst, src)
}
func (m *WasmFuzzyQueryResponse) XXX_Size() int {
	return xxx_messageInfo_WasmFuzzyQueryResponse.Size(m)
}
func (m *WasmFuzzyQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmFuzzyQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WasmFuzzyQueryResponse proto.InternalMessageInfo

func (m *WasmFuzzyQueryResponse) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *WasmFuzzyQueryResponse) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *WasmFuzzyQueryResponse) GetQueryResultItems() []*FuzzyQueryResultItem {
	if m != nil {
		return m.QueryResultItems
	}
	return nil
}

type CreateContrantReq struct {
	// abi字符串
	Abi string `protobuf:"bytes,1,opt,name=Abi,proto3" json:"Abi,omitempty"`
	// 合约别名，方便识别
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,3,opt,name=Note,proto3" json:"Note,omitempty"`
	// 合约字节码
	Code []byte `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	// Fee 交易手续费
	Fee                  int64    `protobuf:"varint,5,opt,name=Fee,proto3" json:"Fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContrantReq) Reset()         { *m = CreateContrantReq{} }
func (m *CreateContrantReq) String() string { return proto.CompactTextString(m) }
func (*CreateContrantReq) ProtoMessage()    {}
func (*CreateContrantReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{27}
}
func (m *CreateContrantReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContrantReq.Unmarshal(m, b)
}
func (m *CreateContrantReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContrantReq.Marshal(b, m, deterministic)
}
func (dst *CreateContrantReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContrantReq.Merge(dst, src)
}
func (m *CreateContrantReq) XXX_Size() int {
	return xxx_messageInfo_CreateContrantReq.Size(m)
}
func (m *CreateContrantReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContrantReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContrantReq proto.InternalMessageInfo

func (m *CreateContrantReq) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateContrantReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContrantReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CreateContrantReq) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateContrantReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type CallContractReq struct {
	// 合约别名，方便识别
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,2,opt,name=Note,proto3" json:"Note,omitempty"`
	// abi 数据
	DataInJson string `protobuf:"bytes,3,opt,name=DataInJson,proto3" json:"DataInJson,omitempty"`
	// 执行动作名称
	ActionName string `protobuf:"bytes,4,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	// Fee 交易手续费
	Fee                  int64    `protobuf:"varint,5,opt,name=Fee,proto3" json:"Fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallContractReq) Reset()         { *m = CallContractReq{} }
func (m *CallContractReq) String() string { return proto.CompactTextString(m) }
func (*CallContractReq) ProtoMessage()    {}
func (*CallContractReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wasm_46d959257a7f74ab, []int{28}
}
func (m *CallContractReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallContractReq.Unmarshal(m, b)
}
func (m *CallContractReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallContractReq.Marshal(b, m, deterministic)
}
func (dst *CallContractReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallContractReq.Merge(dst, src)
}
func (m *CallContractReq) XXX_Size() int {
	return xxx_messageInfo_CallContractReq.Size(m)
}
func (m *CallContractReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallContractReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallContractReq proto.InternalMessageInfo

func (m *CallContractReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallContractReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CallContractReq) GetDataInJson() string {
	if m != nil {
		return m.DataInJson
	}
	return ""
}

func (m *CallContractReq) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *CallContractReq) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func init() {
	proto.RegisterType((*WASMContractObject)(nil), "types.WASMContractObject")
	proto.RegisterType((*WASMContractData)(nil), "types.WASMContractData")
	proto.RegisterType((*LogWASMContractData)(nil), "types.LogWASMContractData")
	proto.RegisterType((*WASMContractState)(nil), "types.WASMContractState")
	proto.RegisterMapType((map[string][]byte)(nil), "types.WASMContractState.StorageEntry")
	proto.RegisterType((*WasmContractAction)(nil), "types.WasmContractAction")
	proto.RegisterType((*CreateWasmContract)(nil), "types.CreateWasmContract")
	proto.RegisterType((*CallWasmContract)(nil), "types.CallWasmContract")
	proto.RegisterType((*ReceiptLocalData)(nil), "types.ReceiptLocalData")
	proto.RegisterType((*ReceiptWASMContract)(nil), "types.ReceiptWASMContract")
	proto.RegisterType((*WASMStateChangeItem)(nil), "types.WASMStateChangeItem")
	proto.RegisterType((*CheckWASMContractNameReq)(nil), "types.CheckWASMContractNameReq")
	proto.RegisterType((*CheckWASMAddrResp)(nil), "types.CheckWASMAddrResp")
	proto.RegisterType((*EstimateWASMGasReq)(nil), "types.EstimateWASMGasReq")
	proto.RegisterType((*EstimateWASMGasResp)(nil), "types.EstimateWASMGasResp")
	proto.RegisterType((*WasmDebugReq)(nil), "types.WasmDebugReq")
	proto.RegisterType((*WasmDebugResp)(nil), "types.WasmDebugResp")
	proto.RegisterType((*WasmGetAbiResp)(nil), "types.WasmGetAbiResp")
	proto.RegisterType((*WasmQueryTableItem)(nil), "types.WasmQueryTableItem")
	proto.RegisterType((*WasmQueryContractTableReq)(nil), "types.WasmQueryContractTableReq")
	proto.RegisterType((*WasmOutItem)(nil), "types.WasmOutItem")
	proto.RegisterType((*QueryResultItem)(nil), "types.QueryResultItem")
	proto.RegisterType((*WasmQueryResponse)(nil), "types.WasmQueryResponse")
	proto.RegisterType((*ConvertJson2AbiReq)(nil), "types.ConvertJson2AbiReq")
	proto.RegisterType((*Json2AbiResponse)(nil), "types.Json2AbiResponse")
	proto.RegisterType((*WasmFuzzyQueryTableReq)(nil), "types.WasmFuzzyQueryTableReq")
	proto.RegisterType((*FuzzyQueryResultItem)(nil), "types.FuzzyQueryResultItem")
	proto.RegisterType((*WasmFuzzyQueryResponse)(nil), "types.WasmFuzzyQueryResponse")
	proto.RegisterType((*CreateContrantReq)(nil), "types.CreateContrantReq")
	proto.RegisterType((*CallContractReq)(nil), "types.CallContractReq")
}

func init() { proto.RegisterFile("wasm.proto", fileDescriptor_wasm_46d959257a7f74ab) }

var fileDescriptor_wasm_46d959257a7f74ab = []byte{
	// 1201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x6f, 0x1c, 0x45,
	0x13, 0xce, 0xec, 0xec, 0x87, 0x5d, 0xde, 0x24, 0xeb, 0x76, 0xb4, 0xef, 0xc4, 0x2f, 0xb2, 0xac,
	0x16, 0x1f, 0x16, 0x20, 0x23, 0xcc, 0x01, 0x14, 0x09, 0xa1, 0xcd, 0xfa, 0x2b, 0xc1, 0xb1, 0xa1,
	0x6d, 0x91, 0x0b, 0x97, 0xde, 0xd9, 0xce, 0x7a, 0xc8, 0xee, 0xcc, 0x66, 0xba, 0xc7, 0x64, 0x73,
	0xe0, 0xc6, 0x09, 0x21, 0x6e, 0x1c, 0x10, 0x37, 0xfe, 0x03, 0x77, 0xf8, 0x65, 0xa8, 0xba, 0x7b,
	0x66, 0x7a, 0x76, 0x16, 0x81, 0x14, 0x4e, 0x5b, 0x55, 0x5d, 0x53, 0xf5, 0x54, 0xd5, 0x53, 0x3d,
	0xb3, 0x00, 0xdf, 0x72, 0x39, 0xdb, 0x9f, 0xa7, 0x89, 0x4a, 0x48, 0x4b, 0x2d, 0xe6, 0x42, 0xd2,
	0xef, 0x3d, 0x20, 0x4f, 0x07, 0x97, 0x4f, 0x86, 0x49, 0xac, 0x52, 0x1e, 0xaa, 0x8b, 0xd1, 0x37,
	0x22, 0x54, 0x84, 0x40, 0x93, 0x8f, 0xc7, 0x69, 0xe0, 0xed, 0x7a, 0x7b, 0xeb, 0x4c, 0xcb, 0xe4,
	0x3d, 0x68, 0x8e, 0xb9, 0xe2, 0x41, 0x63, 0xd7, 0xdb, 0xdb, 0x38, 0xf8, 0xdf, 0xbe, 0x0e, 0xb0,
	0xef, 0x3e, 0x7c, 0xc8, 0x15, 0x67, 0xda, 0x89, 0xec, 0x43, 0x4b, 0x2a, 0xae, 0x44, 0xe0, 0x6b,
	0xef, 0x60, 0x85, 0xf7, 0x25, 0x9e, 0x33, 0xe3, 0x46, 0x7f, 0xf6, 0xa0, 0xb7, 0x1c, 0x8a, 0x04,
	0xd0, 0x09, 0x53, 0xc1, 0x55, 0x92, 0x03, 0xc9, 0x55, 0xc4, 0x17, 0xf3, 0x99, 0xd0, 0x58, 0xd6,
	0x99, 0x96, 0x0b, 0xcc, 0x4d, 0x07, 0x33, 0x81, 0x66, 0x98, 0x8c, 0x45, 0xd0, 0xda, 0xf5, 0xf6,
	0xba, 0x4c, 0xcb, 0x64, 0x1b, 0xd6, 0xf0, 0xf7, 0x94, 0xcb, 0xeb, 0xa0, 0xad, 0xed, 0x85, 0x4e,
	0x7a, 0xe0, 0xf3, 0x51, 0x14, 0x74, 0xb4, 0x19, 0x45, 0xfa, 0xa3, 0x07, 0x5b, 0x67, 0xc9, 0xe4,
	0x3f, 0xc2, 0xe6, 0x3b, 0xd8, 0x5c, 0x1c, 0x06, 0x73, 0x89, 0x23, 0x80, 0x0e, 0x1f, 0x45, 0xfa,
	0xa8, 0x65, 0xa2, 0x5b, 0x95, 0xfe, 0xe9, 0xc1, 0x66, 0xad, 0x8b, 0xe4, 0x1e, 0xb4, 0xe2, 0x24,
	0x0e, 0x85, 0xc6, 0xd2, 0x64, 0x46, 0xc1, 0x0c, 0x32, 0x8b, 0xc2, 0x68, 0x2c, 0xc6, 0x1a, 0xcd,
	0x1a, 0x2b, 0x74, 0xf2, 0x19, 0x74, 0xa4, 0x4a, 0x52, 0x3e, 0xc1, 0x11, 0xf9, 0x7b, 0x1b, 0x07,
	0x6f, 0xfd, 0xdd, 0x88, 0xf6, 0x2f, 0x8d, 0xdf, 0x51, 0xac, 0xd2, 0x05, 0xcb, 0x9f, 0xda, 0x7e,
	0x00, 0x5d, 0xf7, 0x00, 0x5b, 0xf7, 0x5c, 0x2c, 0x6c, 0x33, 0x50, 0x44, 0x50, 0x37, 0x7c, 0x9a,
	0x99, 0x4e, 0x74, 0x99, 0x51, 0x1e, 0x34, 0x3e, 0xf1, 0xe8, 0x1f, 0xc8, 0x3a, 0x2e, 0x67, 0x79,
	0x9e, 0x41, 0xa8, 0xa2, 0x24, 0x26, 0x9f, 0x03, 0xd1, 0x4d, 0x14, 0xee, 0x99, 0x8e, 0xb8, 0x71,
	0x70, 0xdf, 0xc2, 0x1b, 0xd6, 0x1c, 0x4e, 0x6f, 0xb1, 0x15, 0x8f, 0x91, 0x23, 0xe8, 0x85, 0x7c,
	0x3a, 0xad, 0x84, 0xaa, 0x52, 0x77, 0xb8, 0x74, 0x7c, 0x7a, 0x8b, 0xd5, 0x1e, 0x21, 0x77, 0xa0,
	0xa1, 0x16, 0x7a, 0x6e, 0x2d, 0xd6, 0x50, 0x8b, 0x87, 0x1d, 0x5b, 0x14, 0xfd, 0xc5, 0x03, 0x52,
	0x07, 0x83, 0x3d, 0x9f, 0x70, 0x79, 0x16, 0xcd, 0x22, 0x65, 0x87, 0x51, 0xe8, 0xf6, 0xec, 0x8b,
	0x34, 0x0a, 0x4d, 0x4f, 0x6e, 0xb3, 0x42, 0x2f, 0x98, 0xea, 0x3b, 0x4c, 0xb5, 0x6c, 0x34, 0xe4,
	0x40, 0xb1, 0xe0, 0x56, 0xab, 0xca, 0xad, 0x38, 0x51, 0x42, 0x73, 0x19, 0x6d, 0x89, 0x12, 0xf4,
	0x77, 0x0f, 0x7a, 0xcb, 0xe5, 0xbd, 0x0e, 0x34, 0x9d, 0xc0, 0x2f, 0x13, 0x90, 0x3e, 0xb4, 0x6f,
	0x66, 0x57, 0x8b, 0xb9, 0xd0, 0xe8, 0x5a, 0xcc, 0x6a, 0x64, 0x07, 0x80, 0xeb, 0x61, 0x9e, 0x97,
	0x30, 0x1d, 0x4b, 0x79, 0x8e, 0x4b, 0x64, 0xd7, 0xcf, 0xb1, 0xd0, 0xaf, 0xa1, 0xc7, 0x44, 0x28,
	0xa2, 0xb9, 0x3a, 0x4b, 0x42, 0x3e, 0xd5, 0xab, 0xe6, 0x30, 0xab, 0x6b, 0x98, 0x85, 0xab, 0x93,
	0xa5, 0x5f, 0x39, 0xe4, 0x2a, 0x74, 0x3c, 0x9b, 0xa7, 0xc2, 0x9c, 0x99, 0x66, 0x16, 0x3a, 0xfd,
	0xc9, 0x83, 0x2d, 0x1b, 0xde, 0xa5, 0x39, 0x56, 0x83, 0x83, 0x17, 0xf9, 0x2e, 0x5b, 0x8d, 0x50,
	0xe8, 0x86, 0xd6, 0xe7, 0xbc, 0x5c, 0xe9, 0x8a, 0xcd, 0xf5, 0x19, 0x94, 0x2b, 0x5e, 0xb1, 0xe1,
	0x3a, 0x67, 0x52, 0x8c, 0x4f, 0xb8, 0xd4, 0xed, 0x6a, 0xb2, 0x5c, 0xa5, 0x13, 0xd8, 0x42, 0x24,
	0x7a, 0xd1, 0x86, 0xd7, 0x3c, 0x9e, 0x88, 0x47, 0x4a, 0xcc, 0x56, 0x2c, 0x93, 0x5b, 0x56, 0xa3,
	0x5a, 0x96, 0x86, 0x90, 0xa5, 0xa9, 0x88, 0x95, 0x5b, 0x76, 0xc5, 0x46, 0x8f, 0x21, 0x18, 0x5e,
	0x8b, 0xf0, 0xb9, 0x5b, 0x37, 0xe2, 0x67, 0xe2, 0x05, 0x79, 0x17, 0x7a, 0x2e, 0x51, 0x74, 0xa9,
	0x26, 0x75, 0xcd, 0x4e, 0x3f, 0x86, 0xcd, 0x22, 0x0e, 0xd6, 0xc6, 0x84, 0x9c, 0x23, 0x00, 0xf1,
	0x32, 0x92, 0x6a, 0x30, 0x4d, 0x05, 0x1f, 0x1b, 0xdc, 0x6b, 0xac, 0x62, 0xa3, 0xd7, 0x40, 0x8e,
	0xa4, 0x8a, 0x66, 0xb8, 0x30, 0x83, 0xcb, 0x27, 0x27, 0x5c, 0x62, 0x6a, 0x5c, 0xaf, 0xc4, 0x26,
	0x6b, 0xa8, 0xa4, 0x58, 0x83, 0x86, 0xb3, 0x06, 0xe5, 0x74, 0xfc, 0xca, 0x74, 0xfa, 0xd0, 0xe6,
	0xb3, 0x24, 0x8b, 0x95, 0x6d, 0xaa, 0xd5, 0xe8, 0x3b, 0xb0, 0x55, 0xcb, 0x24, 0xe7, 0xd8, 0xd3,
	0x09, 0x97, 0x96, 0xf9, 0x28, 0xd2, 0xb7, 0xa1, 0x8b, 0xf5, 0x1d, 0x8a, 0x51, 0x36, 0x41, 0x30,
	0x7d, 0x68, 0x27, 0x73, 0xbc, 0x1b, 0xb4, 0x53, 0x8b, 0x59, 0x8d, 0x7e, 0x08, 0xb7, 0x1d, 0x3f,
	0x39, 0x27, 0xbb, 0xb0, 0x31, 0x46, 0x05, 0xc7, 0x96, 0x49, 0x0b, 0xdf, 0x35, 0x51, 0x0a, 0x77,
	0xf0, 0x91, 0x13, 0xa1, 0x06, 0xa3, 0x28, 0x4f, 0x8f, 0xcb, 0xec, 0x95, 0xaf, 0x96, 0x43, 0x73,
	0x09, 0x7e, 0x99, 0x89, 0x74, 0x71, 0xc5, 0x47, 0x53, 0x33, 0xfa, 0x37, 0x60, 0x5d, 0xa1, 0xe2,
	0x4c, 0xa1, 0x34, 0xe4, 0xc4, 0x68, 0x14, 0xc4, 0xa0, 0x73, 0xb8, 0x5f, 0x44, 0xc9, 0x27, 0xa5,
	0xa3, 0x61, 0x45, 0xcb, 0x04, 0xf6, 0x56, 0x10, 0xf8, 0x03, 0x68, 0x45, 0x4a, 0xcc, 0x64, 0xd0,
	0xd0, 0xef, 0x81, 0xfc, 0xa2, 0xad, 0x43, 0x63, 0xc6, 0x8f, 0x7e, 0x0a, 0x1b, 0x78, 0x78, 0x91,
	0x29, 0x0d, 0x78, 0x1b, 0xd6, 0xf0, 0xf7, 0x2a, 0xef, 0xdb, 0x3a, 0x2b, 0x74, 0x1c, 0xe7, 0x61,
	0xfe, 0xcd, 0xd0, 0x65, 0x5a, 0xa6, 0x21, 0xdc, 0xd5, 0x71, 0x99, 0x90, 0xd9, 0xf4, 0x9f, 0x43,
	0xec, 0x00, 0xa4, 0xda, 0xf3, 0xf1, 0xe5, 0xc5, 0xb9, 0x2d, 0xdc, 0xb1, 0xe0, 0x5b, 0xe6, 0x59,
	0x92, 0xc5, 0x63, 0x4d, 0x8e, 0x35, 0x66, 0x14, 0xfa, 0x14, 0x36, 0x8b, 0x02, 0xb0, 0xfd, 0x49,
	0x2c, 0x05, 0x79, 0x08, 0xbd, 0x17, 0xd5, 0xcc, 0x38, 0x3b, 0x2c, 0xba, 0x6f, 0x8b, 0x5e, 0x02,
	0xc6, 0x6a, 0xfe, 0xf4, 0x3b, 0x20, 0xc3, 0x24, 0xbe, 0x11, 0xa9, 0x7a, 0x2c, 0x93, 0xf8, 0x40,
	0x4f, 0x57, 0xf7, 0x79, 0xc5, 0xf6, 0x54, 0x6c, 0x58, 0xc8, 0xa0, 0xbc, 0x1a, 0x6d, 0x21, 0xa5,
	0x85, 0xbc, 0x09, 0xb7, 0x07, 0xa3, 0x08, 0x5b, 0xf4, 0x28, 0xc6, 0xd8, 0x96, 0xed, 0x55, 0x23,
	0x7d, 0x1f, 0x7a, 0x65, 0x62, 0x5b, 0x57, 0x00, 0x1d, 0xeb, 0x64, 0xe9, 0x95, 0xab, 0xf4, 0x57,
	0x0f, 0xfa, 0xd8, 0x87, 0xe3, 0xec, 0xd5, 0xab, 0x45, 0x39, 0xcd, 0x7f, 0x4b, 0x8d, 0x0a, 0x17,
	0x1b, 0xcb, 0x5c, 0xec, 0x43, 0xfb, 0x59, 0x92, 0xce, 0xb8, 0xca, 0xf7, 0xd2, 0x68, 0x38, 0x11,
	0xa9, 0x78, 0x6a, 0xd6, 0xd2, 0x67, 0x46, 0x41, 0x2a, 0x48, 0x95, 0xcc, 0xf5, 0x3b, 0xc1, 0x67,
	0x5a, 0xa6, 0x67, 0x70, 0xaf, 0x44, 0xe6, 0xf0, 0xe1, 0x1e, 0xb4, 0xa2, 0x78, 0x2c, 0x5e, 0x6a,
	0x50, 0x3e, 0x33, 0x4a, 0x8d, 0x09, 0x7e, 0x95, 0x09, 0xf4, 0xb7, 0x5a, 0xb1, 0x45, 0x87, 0x5e,
	0xbf, 0xd8, 0x93, 0x15, 0xdc, 0x31, 0x1f, 0x4e, 0xff, 0xb7, 0xdc, 0x59, 0x55, 0xc9, 0x0a, 0x02,
	0x49, 0xd8, 0x34, 0x9f, 0x0d, 0x86, 0x1c, 0xb1, 0xc2, 0x61, 0xf4, 0xc0, 0x1f, 0xd8, 0xcb, 0x61,
	0x9d, 0xa1, 0x88, 0xed, 0x72, 0x80, 0x68, 0x59, 0xdb, 0x9c, 0x17, 0x31, 0xca, 0x68, 0x1b, 0xe2,
	0x85, 0xd9, 0x34, 0x1b, 0x36, 0xb4, 0xdf, 0x0d, 0xc7, 0x42, 0xd8, 0x4e, 0xa3, 0x48, 0x7f, 0xf0,
	0xe0, 0x2e, 0x7e, 0x0f, 0xe4, 0x84, 0xc4, 0x9c, 0x79, 0x06, 0x6f, 0x45, 0x86, 0x86, 0x93, 0x61,
	0x07, 0xa0, 0x46, 0x4a, 0xc7, 0xb2, 0xc4, 0xeb, 0x66, 0x8d, 0xd7, 0x35, 0x34, 0xa3, 0xb6, 0xfe,
	0x0b, 0xf2, 0xd1, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xb1, 0x8b, 0x96, 0x90, 0x0c, 0x00,
	0x00,
}
