// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wasm.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	wasm.proto

It has these top-level messages:
	WASMContractObject
	WASMContractData
	LogWASMContractData
	WASMContractState
	WasmContractAction
	CreateWasmContract
	CallWasmContract
	ReceiptWASMContract
	WASMStateChangeItem
	WASMContractDataCmd
	WASMContractStateCmd
	ReceiptWASMContractCmd
	CheckWASMAddrReq
	CheckWASMAddrResp
	EstimateWASMGasReq
	EstimateWASMGasResp
	WasmDebugReq
	WasmDebugResp
	WasmGetAbiResp
	WasmQuery
	WasmOutItem
	QueryResultItem
	WasmQueryResponse
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 合约对象信息
type WASMContractObject struct {
	Addr  string             `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Data  *WASMContractData  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	State *WASMContractState `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *WASMContractObject) Reset()                    { *m = WASMContractObject{} }
func (m *WASMContractObject) String() string            { return proto.CompactTextString(m) }
func (*WASMContractObject) ProtoMessage()               {}
func (*WASMContractObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WASMContractObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WASMContractObject) GetData() *WASMContractData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WASMContractObject) GetState() *WASMContractState {
	if m != nil {
		return m.State
	}
	return nil
}

// 存放合约固定数据
type WASMContractData struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator" json:"creator,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Addr     string `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	Code     []byte `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash []byte `protobuf:"bytes,6,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	Abi      []byte `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
}

func (m *WASMContractData) Reset()                    { *m = WASMContractData{} }
func (m *WASMContractData) String() string            { return proto.CompactTextString(m) }
func (*WASMContractData) ProtoMessage()               {}
func (*WASMContractData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WASMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *WASMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WASMContractData) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *WASMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WASMContractData) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *WASMContractData) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *WASMContractData) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type LogWASMContractData struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator" json:"creator,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Addr     string `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	CodeHash string `protobuf:"bytes,5,opt,name=codeHash" json:"codeHash,omitempty"`
	AbiHash  string `protobuf:"bytes,6,opt,name=abiHash" json:"abiHash,omitempty"`
}

func (m *LogWASMContractData) Reset()                    { *m = LogWASMContractData{} }
func (m *LogWASMContractData) String() string            { return proto.CompactTextString(m) }
func (*LogWASMContractData) ProtoMessage()               {}
func (*LogWASMContractData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogWASMContractData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *LogWASMContractData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogWASMContractData) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *LogWASMContractData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *LogWASMContractData) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *LogWASMContractData) GetAbiHash() string {
	if m != nil {
		return m.AbiHash
	}
	return ""
}

// 存放合约变化数据
type WASMContractState struct {
	Nonce    uint64            `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Suicided bool              `protobuf:"varint,2,opt,name=suicided" json:"suicided,omitempty"`
	Storage  map[string][]byte `protobuf:"bytes,3,rep,name=storage" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *WASMContractState) Reset()                    { *m = WASMContractState{} }
func (m *WASMContractState) String() string            { return proto.CompactTextString(m) }
func (*WASMContractState) ProtoMessage()               {}
func (*WASMContractState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WASMContractState) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *WASMContractState) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *WASMContractState) GetStorage() map[string][]byte {
	if m != nil {
		return m.Storage
	}
	return nil
}

type WasmContractAction struct {
	// Types that are valid to be assigned to Value:
	//	*WasmContractAction_CreateWasmContract
	//	*WasmContractAction_CallWasmContract
	Value isWasmContractAction_Value `protobuf_oneof:"value"`
	Ty    int32                      `protobuf:"varint,3,opt,name=ty" json:"ty,omitempty"`
}

func (m *WasmContractAction) Reset()                    { *m = WasmContractAction{} }
func (m *WasmContractAction) String() string            { return proto.CompactTextString(m) }
func (*WasmContractAction) ProtoMessage()               {}
func (*WasmContractAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isWasmContractAction_Value interface {
	isWasmContractAction_Value()
}

type WasmContractAction_CreateWasmContract struct {
	CreateWasmContract *CreateWasmContract `protobuf:"bytes,1,opt,name=createWasmContract,oneof"`
}
type WasmContractAction_CallWasmContract struct {
	CallWasmContract *CallWasmContract `protobuf:"bytes,2,opt,name=callWasmContract,oneof"`
}

func (*WasmContractAction_CreateWasmContract) isWasmContractAction_Value() {}
func (*WasmContractAction_CallWasmContract) isWasmContractAction_Value()   {}

func (m *WasmContractAction) GetValue() isWasmContractAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WasmContractAction) GetCreateWasmContract() *CreateWasmContract {
	if x, ok := m.GetValue().(*WasmContractAction_CreateWasmContract); ok {
		return x.CreateWasmContract
	}
	return nil
}

func (m *WasmContractAction) GetCallWasmContract() *CallWasmContract {
	if x, ok := m.GetValue().(*WasmContractAction_CallWasmContract); ok {
		return x.CallWasmContract
	}
	return nil
}

func (m *WasmContractAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WasmContractAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WasmContractAction_OneofMarshaler, _WasmContractAction_OneofUnmarshaler, _WasmContractAction_OneofSizer, []interface{}{
		(*WasmContractAction_CreateWasmContract)(nil),
		(*WasmContractAction_CallWasmContract)(nil),
	}
}

func _WasmContractAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WasmContractAction)
	// value
	switch x := m.Value.(type) {
	case *WasmContractAction_CreateWasmContract:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateWasmContract); err != nil {
			return err
		}
	case *WasmContractAction_CallWasmContract:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CallWasmContract); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WasmContractAction.Value has unexpected type %T", x)
	}
	return nil
}

func _WasmContractAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WasmContractAction)
	switch tag {
	case 1: // value.createWasmContract
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateWasmContract)
		err := b.DecodeMessage(msg)
		m.Value = &WasmContractAction_CreateWasmContract{msg}
		return true, err
	case 2: // value.callWasmContract
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CallWasmContract)
		err := b.DecodeMessage(msg)
		m.Value = &WasmContractAction_CallWasmContract{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WasmContractAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WasmContractAction)
	// value
	switch x := m.Value.(type) {
	case *WasmContractAction_CreateWasmContract:
		s := proto.Size(x.CreateWasmContract)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WasmContractAction_CallWasmContract:
		s := proto.Size(x.CallWasmContract)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 创建wasm合约
type CreateWasmContract struct {
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,2,opt,name=gasLimit" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,3,opt,name=gasPrice" json:"gasPrice,omitempty"`
	// 合约数据
	Code []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// abi数据
	Abi string `protobuf:"bytes,5,opt,name=abi" json:"abi,omitempty"`
	// 合约别名，方便识别
	Alias string `protobuf:"bytes,6,opt,name=alias" json:"alias,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,7,opt,name=note" json:"note,omitempty"`
}

func (m *CreateWasmContract) Reset()                    { *m = CreateWasmContract{} }
func (m *CreateWasmContract) String() string            { return proto.CompactTextString(m) }
func (*CreateWasmContract) ProtoMessage()               {}
func (*CreateWasmContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateWasmContract) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateWasmContract) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CreateWasmContract) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateWasmContract) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateWasmContract) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateWasmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 调用wasm合约
type CallWasmContract struct {
	// 转账金额
	Amount uint64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,2,opt,name=gasLimit" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,3,opt,name=gasPrice" json:"gasPrice,omitempty"`
	// 合约地址
	ContractAddr string `protobuf:"bytes,4,opt,name=contractAddr" json:"contractAddr,omitempty"`
	// 合约id
	// bytes codeHash     = 5;
	// 合约别名，方便识别
	Alias string `protobuf:"bytes,6,opt,name=alias" json:"alias,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,7,opt,name=note" json:"note,omitempty"`
	// 虚拟机解释器类型
	VmType int32 `protobuf:"varint,8,opt,name=vmType" json:"vmType,omitempty"`
	// 执行动作名称
	ActionName string `protobuf:"bytes,9,opt,name=actionName" json:"actionName,omitempty"`
	// 执行参数
	ActionData []byte `protobuf:"bytes,10,opt,name=actionData,proto3" json:"actionData,omitempty"`
}

func (m *CallWasmContract) Reset()                    { *m = CallWasmContract{} }
func (m *CallWasmContract) String() string            { return proto.CompactTextString(m) }
func (*CallWasmContract) ProtoMessage()               {}
func (*CallWasmContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CallWasmContract) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CallWasmContract) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CallWasmContract) GetGasPrice() uint32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CallWasmContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *CallWasmContract) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CallWasmContract) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CallWasmContract) GetVmType() int32 {
	if m != nil {
		return m.VmType
	}
	return 0
}

func (m *CallWasmContract) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *CallWasmContract) GetActionData() []byte {
	if m != nil {
		return m.ActionData
	}
	return nil
}

// 合约创建/调用日志
type ReceiptWASMContract struct {
	Caller       string `protobuf:"bytes,1,opt,name=caller" json:"caller,omitempty"`
	ContractName string `protobuf:"bytes,2,opt,name=contractName" json:"contractName,omitempty"`
	ContractAddr string `protobuf:"bytes,3,opt,name=contractAddr" json:"contractAddr,omitempty"`
	UsedGas      uint64 `protobuf:"varint,4,opt,name=usedGas" json:"usedGas,omitempty"`
}

func (m *ReceiptWASMContract) Reset()                    { *m = ReceiptWASMContract{} }
func (m *ReceiptWASMContract) String() string            { return proto.CompactTextString(m) }
func (*ReceiptWASMContract) ProtoMessage()               {}
func (*ReceiptWASMContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReceiptWASMContract) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptWASMContract) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptWASMContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ReceiptWASMContract) GetUsedGas() uint64 {
	if m != nil {
		return m.UsedGas
	}
	return 0
}

// 用于保存WASM只能合约中的状态数据变更
type WASMStateChangeItem struct {
	Key          string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	PreValue     []byte `protobuf:"bytes,2,opt,name=preValue,proto3" json:"preValue,omitempty"`
	CurrentValue []byte `protobuf:"bytes,3,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
}

func (m *WASMStateChangeItem) Reset()                    { *m = WASMStateChangeItem{} }
func (m *WASMStateChangeItem) String() string            { return proto.CompactTextString(m) }
func (*WASMStateChangeItem) ProtoMessage()               {}
func (*WASMStateChangeItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *WASMStateChangeItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WASMStateChangeItem) GetPreValue() []byte {
	if m != nil {
		return m.PreValue
	}
	return nil
}

func (m *WASMStateChangeItem) GetCurrentValue() []byte {
	if m != nil {
		return m.CurrentValue
	}
	return nil
}

// 存放合约固定数据
type WASMContractDataCmd struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator" json:"creator,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Addr     string `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	Code     string `protobuf:"bytes,5,opt,name=code" json:"code,omitempty"`
	CodeHash string `protobuf:"bytes,6,opt,name=codeHash" json:"codeHash,omitempty"`
}

func (m *WASMContractDataCmd) Reset()                    { *m = WASMContractDataCmd{} }
func (m *WASMContractDataCmd) String() string            { return proto.CompactTextString(m) }
func (*WASMContractDataCmd) ProtoMessage()               {}
func (*WASMContractDataCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WASMContractDataCmd) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *WASMContractDataCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WASMContractDataCmd) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *WASMContractDataCmd) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WASMContractDataCmd) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WASMContractDataCmd) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

// 存放合约变化数据
type WASMContractStateCmd struct {
	Nonce       uint64            `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Suicided    bool              `protobuf:"varint,2,opt,name=suicided" json:"suicided,omitempty"`
	StorageHash string            `protobuf:"bytes,3,opt,name=storageHash" json:"storageHash,omitempty"`
	Storage     map[string]string `protobuf:"bytes,4,rep,name=storage" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WASMContractStateCmd) Reset()                    { *m = WASMContractStateCmd{} }
func (m *WASMContractStateCmd) String() string            { return proto.CompactTextString(m) }
func (*WASMContractStateCmd) ProtoMessage()               {}
func (*WASMContractStateCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WASMContractStateCmd) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *WASMContractStateCmd) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *WASMContractStateCmd) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

func (m *WASMContractStateCmd) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

// 合约创建/调用日志
type ReceiptWASMContractCmd struct {
	Caller string `protobuf:"bytes,1,opt,name=caller" json:"caller,omitempty"`
	// 合约创建时才会返回此内容
	ContractName string `protobuf:"bytes,2,opt,name=contractName" json:"contractName,omitempty"`
	ContractAddr string `protobuf:"bytes,3,opt,name=contractAddr" json:"contractAddr,omitempty"`
	UsedGas      uint64 `protobuf:"varint,4,opt,name=usedGas" json:"usedGas,omitempty"`
	// 创建合约返回的代码
	Ret string `protobuf:"bytes,5,opt,name=ret" json:"ret,omitempty"`
}

func (m *ReceiptWASMContractCmd) Reset()                    { *m = ReceiptWASMContractCmd{} }
func (m *ReceiptWASMContractCmd) String() string            { return proto.CompactTextString(m) }
func (*ReceiptWASMContractCmd) ProtoMessage()               {}
func (*ReceiptWASMContractCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReceiptWASMContractCmd) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *ReceiptWASMContractCmd) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ReceiptWASMContractCmd) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ReceiptWASMContractCmd) GetUsedGas() uint64 {
	if m != nil {
		return m.UsedGas
	}
	return 0
}

func (m *ReceiptWASMContractCmd) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

type CheckWASMAddrReq struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *CheckWASMAddrReq) Reset()                    { *m = CheckWASMAddrReq{} }
func (m *CheckWASMAddrReq) String() string            { return proto.CompactTextString(m) }
func (*CheckWASMAddrReq) ProtoMessage()               {}
func (*CheckWASMAddrReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CheckWASMAddrReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type CheckWASMAddrResp struct {
	Contract     bool   `protobuf:"varint,1,opt,name=contract" json:"contract,omitempty"`
	ContractAddr string `protobuf:"bytes,2,opt,name=contractAddr" json:"contractAddr,omitempty"`
	ContractName string `protobuf:"bytes,3,opt,name=contractName" json:"contractName,omitempty"`
	AliasName    string `protobuf:"bytes,4,opt,name=aliasName" json:"aliasName,omitempty"`
}

func (m *CheckWASMAddrResp) Reset()                    { *m = CheckWASMAddrResp{} }
func (m *CheckWASMAddrResp) String() string            { return proto.CompactTextString(m) }
func (*CheckWASMAddrResp) ProtoMessage()               {}
func (*CheckWASMAddrResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CheckWASMAddrResp) GetContract() bool {
	if m != nil {
		return m.Contract
	}
	return false
}

func (m *CheckWASMAddrResp) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *CheckWASMAddrResp) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *CheckWASMAddrResp) GetAliasName() string {
	if m != nil {
		return m.AliasName
	}
	return ""
}

type EstimateWASMGasReq struct {
	To     string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Code   []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Caller string `protobuf:"bytes,3,opt,name=caller" json:"caller,omitempty"`
	Amount uint64 `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *EstimateWASMGasReq) Reset()                    { *m = EstimateWASMGasReq{} }
func (m *EstimateWASMGasReq) String() string            { return proto.CompactTextString(m) }
func (*EstimateWASMGasReq) ProtoMessage()               {}
func (*EstimateWASMGasReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *EstimateWASMGasReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EstimateWASMGasReq) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EstimateWASMGasReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *EstimateWASMGasReq) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type EstimateWASMGasResp struct {
	Gas uint64 `protobuf:"varint,1,opt,name=gas" json:"gas,omitempty"`
}

func (m *EstimateWASMGasResp) Reset()                    { *m = EstimateWASMGasResp{} }
func (m *EstimateWASMGasResp) String() string            { return proto.CompactTextString(m) }
func (*EstimateWASMGasResp) ProtoMessage()               {}
func (*EstimateWASMGasResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *EstimateWASMGasResp) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

type WasmDebugReq struct {
	// 0 query, 1 set, -1 clear
	Optype int32 `protobuf:"varint,1,opt,name=optype" json:"optype,omitempty"`
}

func (m *WasmDebugReq) Reset()                    { *m = WasmDebugReq{} }
func (m *WasmDebugReq) String() string            { return proto.CompactTextString(m) }
func (*WasmDebugReq) ProtoMessage()               {}
func (*WasmDebugReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *WasmDebugReq) GetOptype() int32 {
	if m != nil {
		return m.Optype
	}
	return 0
}

type WasmDebugResp struct {
	DebugStatus string `protobuf:"bytes,1,opt,name=debugStatus" json:"debugStatus,omitempty"`
}

func (m *WasmDebugResp) Reset()                    { *m = WasmDebugResp{} }
func (m *WasmDebugResp) String() string            { return proto.CompactTextString(m) }
func (*WasmDebugResp) ProtoMessage()               {}
func (*WasmDebugResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *WasmDebugResp) GetDebugStatus() string {
	if m != nil {
		return m.DebugStatus
	}
	return ""
}

type WasmGetAbiResp struct {
	Abi []byte `protobuf:"bytes,1,opt,name=abi,proto3" json:"abi,omitempty"`
}

func (m *WasmGetAbiResp) Reset()                    { *m = WasmGetAbiResp{} }
func (m *WasmGetAbiResp) String() string            { return proto.CompactTextString(m) }
func (*WasmGetAbiResp) ProtoMessage()               {}
func (*WasmGetAbiResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *WasmGetAbiResp) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

type WasmQuery struct {
	ContractAddr string `protobuf:"bytes,1,opt,name=contractAddr" json:"contractAddr,omitempty"`
	ActionName   string `protobuf:"bytes,2,opt,name=actionName" json:"actionName,omitempty"`
	Abidata      []byte `protobuf:"bytes,3,opt,name=abidata,proto3" json:"abidata,omitempty"`
}

func (m *WasmQuery) Reset()                    { *m = WasmQuery{} }
func (m *WasmQuery) String() string            { return proto.CompactTextString(m) }
func (*WasmQuery) ProtoMessage()               {}
func (*WasmQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *WasmQuery) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *WasmQuery) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *WasmQuery) GetAbidata() []byte {
	if m != nil {
		return m.Abidata
	}
	return nil
}

type WasmOutItem struct {
	ItemType string `protobuf:"bytes,1,opt,name=ItemType" json:"ItemType,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *WasmOutItem) Reset()                    { *m = WasmOutItem{} }
func (m *WasmOutItem) String() string            { return proto.CompactTextString(m) }
func (*WasmOutItem) ProtoMessage()               {}
func (*WasmOutItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *WasmOutItem) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *WasmOutItem) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryResultItem struct {
	ItemType   string `protobuf:"bytes,1,opt,name=ItemType" json:"ItemType,omitempty"`
	ResultJSON string `protobuf:"bytes,2,opt,name=resultJSON" json:"resultJSON,omitempty"`
}

func (m *QueryResultItem) Reset()                    { *m = QueryResultItem{} }
func (m *QueryResultItem) String() string            { return proto.CompactTextString(m) }
func (*QueryResultItem) ProtoMessage()               {}
func (*QueryResultItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *QueryResultItem) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *QueryResultItem) GetResultJSON() string {
	if m != nil {
		return m.ResultJSON
	}
	return ""
}

type WasmQueryResponse struct {
	QueryResultItems []*QueryResultItem `protobuf:"bytes,1,rep,name=queryResultItems" json:"queryResultItems,omitempty"`
}

func (m *WasmQueryResponse) Reset()                    { *m = WasmQueryResponse{} }
func (m *WasmQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*WasmQueryResponse) ProtoMessage()               {}
func (*WasmQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *WasmQueryResponse) GetQueryResultItems() []*QueryResultItem {
	if m != nil {
		return m.QueryResultItems
	}
	return nil
}

func init() {
	proto.RegisterType((*WASMContractObject)(nil), "types.WASMContractObject")
	proto.RegisterType((*WASMContractData)(nil), "types.WASMContractData")
	proto.RegisterType((*LogWASMContractData)(nil), "types.LogWASMContractData")
	proto.RegisterType((*WASMContractState)(nil), "types.WASMContractState")
	proto.RegisterType((*WasmContractAction)(nil), "types.WasmContractAction")
	proto.RegisterType((*CreateWasmContract)(nil), "types.CreateWasmContract")
	proto.RegisterType((*CallWasmContract)(nil), "types.CallWasmContract")
	proto.RegisterType((*ReceiptWASMContract)(nil), "types.ReceiptWASMContract")
	proto.RegisterType((*WASMStateChangeItem)(nil), "types.WASMStateChangeItem")
	proto.RegisterType((*WASMContractDataCmd)(nil), "types.WASMContractDataCmd")
	proto.RegisterType((*WASMContractStateCmd)(nil), "types.WASMContractStateCmd")
	proto.RegisterType((*ReceiptWASMContractCmd)(nil), "types.ReceiptWASMContractCmd")
	proto.RegisterType((*CheckWASMAddrReq)(nil), "types.CheckWASMAddrReq")
	proto.RegisterType((*CheckWASMAddrResp)(nil), "types.CheckWASMAddrResp")
	proto.RegisterType((*EstimateWASMGasReq)(nil), "types.EstimateWASMGasReq")
	proto.RegisterType((*EstimateWASMGasResp)(nil), "types.EstimateWASMGasResp")
	proto.RegisterType((*WasmDebugReq)(nil), "types.WasmDebugReq")
	proto.RegisterType((*WasmDebugResp)(nil), "types.WasmDebugResp")
	proto.RegisterType((*WasmGetAbiResp)(nil), "types.WasmGetAbiResp")
	proto.RegisterType((*WasmQuery)(nil), "types.WasmQuery")
	proto.RegisterType((*WasmOutItem)(nil), "types.WasmOutItem")
	proto.RegisterType((*QueryResultItem)(nil), "types.QueryResultItem")
	proto.RegisterType((*WasmQueryResponse)(nil), "types.WasmQueryResponse")
}

func init() { proto.RegisterFile("wasm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xde, 0xb1, 0xc7, 0x3f, 0x53, 0xf6, 0x2e, 0x4e, 0x67, 0x15, 0x86, 0x08, 0xad, 0xa2, 0x96,
	0x58, 0x2c, 0x21, 0x59, 0x22, 0x5c, 0xd0, 0x4a, 0x08, 0x25, 0x4e, 0x94, 0x00, 0x9b, 0x04, 0xda,
	0x2b, 0xf6, 0xdc, 0x9e, 0x69, 0x39, 0xc3, 0x7a, 0x7e, 0x76, 0xba, 0x67, 0x91, 0x1f, 0x00, 0x89,
	0x1b, 0x27, 0x6e, 0x70, 0x82, 0x23, 0x2f, 0x01, 0x8f, 0xc3, 0x53, 0xa0, 0xea, 0xf9, 0x6b, 0x7b,
	0x26, 0xe2, 0x47, 0x68, 0xf7, 0xe4, 0xae, 0xea, 0xea, 0xa9, 0xaf, 0xaa, 0xbe, 0xfe, 0xdc, 0x00,
	0xdf, 0x72, 0x19, 0xce, 0x92, 0x34, 0x56, 0x31, 0xe9, 0xa9, 0x4d, 0x22, 0x24, 0xfd, 0xce, 0x02,
	0xf2, 0xfc, 0x64, 0x71, 0x35, 0x8f, 0x23, 0x95, 0x72, 0x4f, 0xdd, 0x2c, 0xbf, 0x11, 0x9e, 0x22,
	0x04, 0x6c, 0xee, 0xfb, 0xa9, 0x6b, 0x1d, 0x59, 0x53, 0x87, 0xe9, 0x35, 0xf9, 0x00, 0x6c, 0x9f,
	0x2b, 0xee, 0x76, 0x8e, 0xac, 0xe9, 0xe8, 0xf8, 0xed, 0x99, 0xfe, 0xc0, 0xcc, 0x3c, 0x7c, 0xc6,
	0x15, 0x67, 0x3a, 0x88, 0xcc, 0xa0, 0x27, 0x15, 0x57, 0xc2, 0xed, 0xea, 0x68, 0xb7, 0x25, 0x7a,
	0x81, 0xfb, 0x2c, 0x0f, 0xa3, 0xbf, 0x59, 0x30, 0xd9, 0xfd, 0x14, 0x71, 0x61, 0xe0, 0xa5, 0x82,
	0xab, 0xb8, 0x04, 0x52, 0x9a, 0x88, 0x2f, 0xe2, 0xa1, 0xd0, 0x58, 0x1c, 0xa6, 0xd7, 0xe4, 0x21,
	0xf4, 0xf8, 0x3a, 0xe0, 0x52, 0xa7, 0x74, 0x58, 0x6e, 0x54, 0x95, 0xd8, 0x46, 0x25, 0x04, 0x6c,
	0x2f, 0xf6, 0x85, 0xdb, 0x3b, 0xb2, 0xa6, 0x63, 0xa6, 0xd7, 0xe4, 0x10, 0x86, 0xf8, 0x7b, 0xc9,
	0xe5, 0xad, 0xdb, 0xd7, 0xfe, 0xca, 0x26, 0x13, 0xe8, 0xf2, 0x65, 0xe0, 0x0e, 0xb4, 0x1b, 0x97,
	0xf4, 0x17, 0x0b, 0xf6, 0x9f, 0xc6, 0xab, 0xd7, 0x86, 0xd8, 0x44, 0xd7, 0xd3, 0xfe, 0x1a, 0x9d,
	0x0b, 0x03, 0xbe, 0x0c, 0x2a, 0xe0, 0x0e, 0x2b, 0x4d, 0xfa, 0x87, 0x05, 0x7b, 0x8d, 0x8e, 0x63,
	0xd6, 0x28, 0x8e, 0x3c, 0xa1, 0x11, 0xda, 0x2c, 0x37, 0x30, 0x83, 0xcc, 0x02, 0x2f, 0xf0, 0x85,
	0xaf, 0x31, 0x0e, 0x59, 0x65, 0x93, 0x4f, 0x61, 0x20, 0x55, 0x9c, 0xf2, 0x15, 0x8e, 0xb3, 0x3b,
	0x1d, 0x1d, 0xbf, 0x77, 0xd7, 0x38, 0x67, 0x8b, 0x3c, 0xee, 0x3c, 0x52, 0xe9, 0x86, 0x95, 0xa7,
	0x0e, 0x9f, 0xc0, 0xd8, 0xdc, 0xc0, 0x86, 0xbe, 0x10, 0x9b, 0xa2, 0x45, 0xb8, 0x44, 0x50, 0xaf,
	0xf8, 0x3a, 0xcb, 0xfb, 0x33, 0x66, 0xb9, 0xf1, 0xa4, 0xf3, 0xb1, 0x45, 0x7f, 0x47, 0x86, 0x72,
	0x19, 0x96, 0x79, 0x4e, 0x3c, 0x15, 0xc4, 0x11, 0xf9, 0x02, 0x88, 0x6e, 0xad, 0x30, 0xf7, 0xf4,
	0x17, 0x47, 0xc7, 0xef, 0x14, 0xf0, 0xe6, 0x8d, 0x80, 0xcb, 0x7b, 0xac, 0xe5, 0x18, 0x39, 0x87,
	0x89, 0xc7, 0xd7, 0xeb, 0xad, 0x4f, 0x6d, 0xd3, 0x7c, 0xbe, 0xb3, 0x7d, 0x79, 0x8f, 0x35, 0x8e,
	0x90, 0x07, 0xd0, 0x51, 0x1b, 0x3d, 0xcc, 0x1e, 0xeb, 0xa8, 0xcd, 0xe9, 0xa0, 0x28, 0x8a, 0xfe,
	0x64, 0x01, 0x69, 0x82, 0xc1, 0x9e, 0xaf, 0xb8, 0x7c, 0x1a, 0x84, 0x41, 0x9e, 0xce, 0x66, 0x95,
	0x5d, 0xec, 0x7d, 0x99, 0x06, 0x5e, 0x7e, 0x87, 0xee, 0xb3, 0xca, 0xae, 0xf8, 0x6b, 0x1b, 0xfc,
	0x2d, 0x38, 0x9a, 0x93, 0x03, 0x97, 0x35, 0xbb, 0xfa, 0x3b, 0xec, 0x8a, 0x62, 0x25, 0x34, 0x99,
	0x91, 0x87, 0xb1, 0x12, 0xf4, 0xfb, 0x0e, 0x4c, 0x76, 0x0b, 0x24, 0x07, 0xd0, 0xe7, 0x61, 0x9c,
	0x45, 0xaa, 0xe0, 0x49, 0x61, 0xfd, 0x67, 0xd0, 0x14, 0xc6, 0x5e, 0x39, 0xc2, 0x9a, 0xde, 0x5b,
	0xbe, 0x7f, 0x0e, 0x19, 0xd1, 0xbd, 0x0a, 0x9f, 0x6d, 0x12, 0xe1, 0x0e, 0x75, 0xbb, 0x0b, 0x8b,
	0x3c, 0x02, 0xe0, 0x9a, 0x20, 0xd7, 0x78, 0xd9, 0x1c, 0x7d, 0xc2, 0xf0, 0xd4, 0xfb, 0x78, 0x5d,
	0x5d, 0xd0, 0x0d, 0x34, 0x3c, 0xf4, 0x07, 0x0b, 0xf6, 0x99, 0xf0, 0x44, 0x90, 0x28, 0x93, 0xdc,
	0x98, 0x0f, 0xc7, 0x2d, 0xca, 0x7b, 0x5d, 0x58, 0x66, 0x55, 0xd7, 0xf5, 0xf5, 0xde, 0xf2, 0x35,
	0x2a, 0xef, 0xb6, 0x54, 0xee, 0xc2, 0x20, 0x93, 0xc2, 0xbf, 0xe0, 0x52, 0x37, 0xc6, 0x66, 0xa5,
	0x49, 0x57, 0xb0, 0x8f, 0x48, 0xf4, 0xf5, 0x9a, 0xdf, 0xf2, 0x68, 0x25, 0x3e, 0x53, 0x22, 0x6c,
	0xb9, 0x42, 0x87, 0x30, 0x4c, 0x52, 0xf1, 0xb5, 0x71, 0x8b, 0x2a, 0x5b, 0x43, 0xc8, 0xd2, 0x54,
	0x44, 0x2a, 0xdf, 0xef, 0xea, 0xfd, 0x2d, 0x1f, 0xfd, 0xd9, 0xca, 0x33, 0x99, 0x82, 0x36, 0x0f,
	0xfd, 0xd7, 0xa2, 0xc2, 0xce, 0x1d, 0x2a, 0x6c, 0xe8, 0x1c, 0xfd, 0xd3, 0x82, 0x87, 0x0d, 0xc1,
	0x41, 0x80, 0xff, 0x5e, 0xd0, 0x8e, 0x60, 0x54, 0x48, 0x93, 0xce, 0x94, 0x43, 0x35, 0x5d, 0xe4,
	0xb4, 0x96, 0x3c, 0x5b, 0x4b, 0xde, 0xf4, 0x2e, 0xc9, 0x9b, 0x87, 0xfe, 0xff, 0xa3, 0x7a, 0x8e,
	0xa9, 0x7a, 0xbf, 0x5a, 0x70, 0xd0, 0xc2, 0x43, 0x2c, 0xf7, 0x8d, 0x51, 0x11, 0x0b, 0x48, 0x85,
	0x2a, 0x35, 0x26, 0x15, 0x8a, 0x3e, 0x86, 0xc9, 0xfc, 0x56, 0x78, 0x2f, 0x10, 0x23, 0x1e, 0x66,
	0xe2, 0x65, 0xdb, 0xdb, 0x81, 0xfe, 0x68, 0xc1, 0xde, 0x4e, 0xa0, 0x4c, 0xf2, 0x69, 0x1b, 0xca,
	0x3d, 0x64, 0x95, 0xdd, 0x40, 0xda, 0x69, 0x41, 0xba, 0x5b, 0x71, 0xb7, 0xa5, 0xe2, 0x77, 0xc1,
	0xd1, 0x14, 0xd4, 0x01, 0x39, 0xfd, 0x6a, 0x07, 0xbd, 0x05, 0x72, 0x2e, 0x55, 0x10, 0xa2, 0x32,
	0x9f, 0x2c, 0xae, 0x2e, 0xb8, 0xc4, 0x0a, 0x50, 0xc7, 0xe3, 0x02, 0x7f, 0x47, 0xc5, 0x15, 0x53,
	0x3b, 0x86, 0xde, 0xd6, 0x53, 0xe8, 0x6e, 0x4d, 0xa1, 0x96, 0x4d, 0xdb, 0x94, 0x4d, 0xfa, 0x3e,
	0xec, 0x37, 0x32, 0xc9, 0x04, 0x5b, 0xba, 0xe2, 0xb2, 0x60, 0x2e, 0x2e, 0xe9, 0x63, 0x18, 0xa3,
	0x0e, 0x9f, 0x89, 0x65, 0xb6, 0x42, 0x30, 0x07, 0xd0, 0x8f, 0x13, 0xe4, 0x9e, 0x0e, 0xea, 0xb1,
	0xc2, 0xa2, 0x1f, 0xc2, 0x7d, 0x23, 0x4e, 0x26, 0x48, 0x6a, 0x1f, 0x0d, 0x64, 0x65, 0x26, 0x0b,
	0xf8, 0xa6, 0x8b, 0x52, 0x78, 0x80, 0x47, 0x2e, 0x84, 0x3a, 0x59, 0x06, 0x65, 0x7a, 0xfc, 0xd7,
	0xb0, 0xea, 0x97, 0x4d, 0x00, 0x0e, 0xc6, 0x7c, 0x95, 0x89, 0x74, 0xd3, 0x18, 0x82, 0xd5, 0x32,
	0x84, 0x6d, 0xc5, 0xed, 0x34, 0x14, 0x37, 0x7f, 0x9e, 0xe8, 0x97, 0x63, 0xae, 0x3a, 0xa5, 0x49,
	0x3f, 0x81, 0x11, 0xa6, 0xba, 0xc9, 0x94, 0x56, 0xb4, 0x43, 0x18, 0xe2, 0xef, 0xb3, 0xb2, 0x54,
	0x87, 0x55, 0x36, 0x4e, 0xe0, 0xac, 0x7c, 0x7b, 0x8e, 0x99, 0x5e, 0xd3, 0x2b, 0x78, 0x4b, 0xa3,
	0x64, 0x42, 0x66, 0xeb, 0xbf, 0xff, 0xc4, 0x23, 0x80, 0x54, 0x47, 0x7e, 0xbe, 0xb8, 0xb9, 0x2e,
	0x71, 0xd6, 0x1e, 0xfa, 0x1c, 0xf6, 0xaa, 0xc2, 0xb1, 0x37, 0x71, 0x24, 0x05, 0x39, 0x85, 0xc9,
	0xcb, 0xed, 0x1c, 0xd8, 0x58, 0xd4, 0x83, 0x83, 0x42, 0x0f, 0x76, 0x20, 0xb0, 0x46, 0xfc, 0xb2,
	0xaf, 0x1f, 0xdc, 0x1f, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x03, 0x2b, 0x32, 0x98, 0x7e, 0x0b,
	0x00, 0x00,
}
